name: Build T3S3 Companion BLE (Cyrillic)

on:
  workflow_dispatch:
  push:
    branches:
      - 'PowerSaving-v17-cyrillic'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Firmware
        env:
          FIRMWARE_VERSION: PowerSaving17.1.2-cyr2
        run: |
          mkdir -p out
          /usr/bin/env bash build.sh build-firmware LilyGo_T3S3_sx1262_companion_radio_ble

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: LilyGo_T3S3_sx1262_companion_radio_ble-cyrillic
          path: out
