name: Build T3S3 / Heltec V3 Companion BLE (Cyrillic)

on:
  workflow_dispatch:
  push:
    branches:
      - 'PowerSaving-v17-cyrillic'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - LilyGo_T3S3_sx1262_companion_radio_ble
          - Heltec_v3_companion_radio_ble
    steps:

      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Firmware
        env:
          FIRMWARE_VERSION: PowerSaving17.1.2-cyr3
        run: |
          mkdir -p out
          /usr/bin/env bash build.sh build-firmware ${{ matrix.target }}

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}-cyrillic
          path: out
